import { createContext } from "react";

export default createContext({
  isAdminMode: false,
  setAdminMode: () => {},
  isCollapsed: false,
  setIsCollapsed: () => {},
  currentTabSelected: false,
  setCurrentTabSelected: () => {},
  addProductToMenu: () => {},
  updateProductInMenu: () => {},
  menuData: [],
  setMenuData: () => {},
  handleAdd: () => {},
  handleDelete: () => {},
  handleEdit: () => {},
  resetMenu: () => {},
  basket: [],
  newProduct: {},
  setNewProduct: () => {},
  handleAddToBasket: () => {},
  calculateTotal: () =>{},
  productSelected: {},
  handleDeleteBasket: () => {},
  setProductSelected: () => {},
  removeProductFromMenuAndBasket: () => {},
  handleProductSelected: () => {},

  titleEditRef: {},
});